// AUTO-GENERATED by obsidian-smart-env/build/build_env_config.js. DO NOT EDIT.

import connections_lists from './src/collections/connections_lists.js';

import { ConnectionsList } from './src/items/connections_list.js';

import { render as connections_codeblock_component } from './src/components/connections_codeblock.js';
import { render as connections_footer_view_component } from './src/components/connections_footer_view.js';
import { render as connections_graph_v1_component } from './src/components/connections-graph/v1.js';
import { render as connections_list_item_v3_component, settings_config as connections_list_item_v3_component_settings_config } from './src/components/connections-list-item/v3.js';
import { render as connections_list_v3_component, display_name as connections_list_v3_component_display_name } from './src/components/connections-list/v3.js';
import { render as connections_list_v4_component, settings_config as connections_list_v4_component_settings_config, display_name as connections_list_v4_component_display_name } from './src/components/connections-list/v4.js';
import { render as connections_settings_header_component } from './src/components/connections-settings/header.js';
import { render as connections_settings_lookup_callout_component } from './src/components/connections-settings/lookup_callout.js';
import { render as connections_view_v3_component } from './src/components/connections-view/v3.js';
import { render as lookup_item_view_component, version as lookup_item_view_component_version } from './src/components/lookup/item_view.js';
import { render as lookup_v3_list_component, version as lookup_v3_list_component_version } from './src/components/lookup/v3/list.js';
import { render as lookup_v3_list_item_component, version as lookup_v3_list_item_component_version } from './src/components/lookup/v3/list_item.js';

import { pre_process as connections_list_pre_process_action, pre_process as connections_list_pre_process_action_pre_process } from './src/actions/connections-list/pre_process.js';


export const smart_env_config = {
  collections: {
    connections_lists
  },
  items: {
    connections_list: { class: ConnectionsList, version: "2.4.5" }
  },
  modules: {

  },
  components: {
    connections_codeblock: { render: connections_codeblock_component, version: "2.4.5" },
    connections_footer_view: { render: connections_footer_view_component, version: "2.4.5" },
    connections_graph_v1: { render: connections_graph_v1_component, version: "2.4.5" },
    connections_list_item_v3: { render: connections_list_item_v3_component, settings_config: connections_list_item_v3_component_settings_config, version: "2.4.5" },
    connections_list_v3: { render: connections_list_v3_component, display_name: connections_list_v3_component_display_name, version: "2.4.5" },
    connections_list_v4: { render: connections_list_v4_component, settings_config: connections_list_v4_component_settings_config, display_name: connections_list_v4_component_display_name, version: "2.4.5" },
    connections_settings_header: { render: connections_settings_header_component, version: "2.4.5" },
    connections_settings_lookup_callout: { render: connections_settings_lookup_callout_component, version: "2.4.5" },
    connections_view_v3: { render: connections_view_v3_component, version: "2.4.5" },
    lookup_item_view: { render: lookup_item_view_component, version: lookup_item_view_component_version },
    lookup_v3_list: { render: lookup_v3_list_component, version: lookup_v3_list_component_version },
    lookup_v3_list_item: { render: lookup_v3_list_item_component, version: lookup_v3_list_item_component_version }
  },
  actions: {
    connections_list_pre_process: { action: connections_list_pre_process_action, pre_process: connections_list_pre_process_action_pre_process, version: "2.4.5" }
  }
};
